<a href="https://colab.research.google.com/github/mobarakol/tutorial_notebooks/blob/main/raw_mri_preproc_unzip_rename_folder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!ls endonasal_mri_v2

MRIs                            OneDrive_19_9-6-2024.zip
OneDrive_11_9-6-2024.zip        OneDrive_20_9-6-2024.zip
OneDrive_12_9-6-2024.zip        OneDrive_21_9-6-2024.zip
OneDrive_13_9-6-2024.zip        OneDrive_22_9-6-2024.zip
OneDrive_14_9-6-2024.zip        OneDrive_23_9-6-2024.zip
OneDrive_15_9-6-2024.zip        OneDrive_25_9-6-2024.zip
OneDrive_16_9-6-2024.zip        OneDrive_4_9-6-2024_1-10.zip
OneDrive_17_9-6-2024.zip        OneDrive_9_9-6-2024_100-109.zip
OneDrive_18_9-6-2024.zip


In [ ]:
from glob import glob
zips = glob('endonasal_mri_v2/*.zip')
for zip1 in zips:
    print(zip1)
    !unzip -o -q $zip1 -d endonasal_mri_v2/MRIs_ALL

endonasal_mri_v2/OneDrive_23_9-6-2024.zip
warning [endonasal_mri_v2/OneDrive_23_9-6-2024.zip]:  5324800 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  5324800
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  93779
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  93779
file #3:  bad zipfile offset (local header sig):  5418824
file #4:  bad zipfile offset (local header sig):  5419071
file #5:  bad zipfile offset (local header sig):  5773922
file #6:  bad zipfile offset (local header sig):  5841393
file #7:  bad zipfile offset (local header sig):  5841639
file #8:  bad zipfile offset (local header sig):  5841887
file #9:  bad zipfile offset (local header sig):  6101148
endonasal_mri_v2/OneDrive_12_9-6-2024.zip
endonasal_mri_v2/OneDrive_15_9-6-2024.zip
endonasal_mri_v2/OneDrive_25_9-6-2024.zip
endonasal_mri_v2/OneDrive_22_9-6-2024.zip
warning [end

In [ ]:
from glob import glob
zips = glob('endonasal_mri_v2/new/*.zip')
for zip1 in zips:
    print(zip1)
    !unzip -o -q $zip1 -d endonasal_mri_v2/MRIs_ALL

endonasal_mri_v2/new/OneDrive_31_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_36_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_37_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_30_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_28_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_29_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_32_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_35_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_34_9-7-2024.zip
endonasal_mri_v2/new/OneDrive_33_9-7-2024.zip


In [ ]:
!ls endonasal_mri_v2/MRIs_ALL

100_T1.nii.gz         17_tumor_f.nii.gz     59_carotids_f.nii.gz
100_T2_f.nii.gz       18_T1.nii.gz          59_tumor_f.nii.gz
100_carotids_f.nii.gz 18_carotids_f.nii.gz  5_T1.nii.gz
100_tumor_f.nii.gz    18_tumor_f.nii.gz     5_T2_f.nii.gz
101_T1.nii.gz         19_T1.nii.gz          5_carotids_f.nii.gz
101_T2_f.nii.gz       19_carotids_f.nii.gz  5_tumor_f.nii.gz
101_carotids_f.nii.gz 19_tumor_f.nii.gz     60_T1.nii.gz
101_tumor_f.nii.gz    1_T1.nii.gz           60_T2_f.nii.gz
102_T1.nii.gz         1_T2_f.nii.gz         60_carotids_f.nii.gz
102_T2_f.nii.gz       1_carotids_f.nii.gz   60_tumor_f.nii.gz
102_carotids_f.nii.gz 1_tumor_f.nii.gz      61_T1.nii.gz
102_tumor_f.nii.gz    20_T1.nii.gz          61_carotids_f.nii.gz
103_T1.nii.gz         20_carotids_f.nii.gz  61_tumor_f.nii.gz
103_T2_f.nii.gz       20_tumor_f.nii.gz     62_T1.nii.gz
103_carotids_f.nii.gz 21_T1.nii.gz          62_carotids_f.nii.gz
103_tumor_f.nii.gz    21_carotids_f.nii.gz  62_tumor_f.nii.gz
104_T1.nii.gz         2

In [ ]:
from glob import glob
import os
import numpy as np

mris = glob('endonasal_mri_v2/MRIs_ALL/*_T1.nii.gz')
mri_int = []
for mri in mris:
    mri_file = os.path.basename(mri).split('_')[0]
    mri_int.append(mri_file)
#     print(mri_file)
mri_int = np.array(mri_int).astype(int)
mri_int.sort()
print(mri_int)

for i in range(1,137,1):
    if i != mri_int[i-1]:
        print(i)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136]


In [ ]:
from glob import glob
import os
import numpy as np

mris = glob('endonasal_mri_v2/MRIs_ALL/*_T2_f.nii.gz')
mri_int = []
for mri in mris:
    mri_file = os.path.basename(mri).split('_')[0]
    mri_int.append(mri_file)
#     print(mri_file)
mri_int = np.array(mri_int).astype(int)
mri_int.sort()
print(len(mri_int))
all_idx = np.zeros(137)
for i in mri_int:
    all_idx[i] = 1

missing_cases = []
for i in range(1,137,1):
    if all_idx[i] != 1:
        missing_cases.append(i)

np.array(missing_cases)

100


array([  2,   4,   9,  10,  18,  19,  20,  21,  23,  24,  33,  35,  37,
        39,  48,  54,  61,  62,  71,  73,  77,  80,  85,  86,  87,  90,
        97, 107, 108, 111, 119, 121, 124, 131, 132, 134])

In [ ]:
from glob import glob
import os
import numpy as np

mris = glob('endonasal_mri_v2/MRIs_ALL/*_carotids_f.nii.gz')
mri_int = []
for mri in mris:
    mri_file = os.path.basename(mri).split('_')[0]
    mri_int.append(mri_file)
#     print(mri_file)
mri_int = np.array(mri_int).astype(int)
mri_int.sort()
print(len(mri_int))
all_idx = np.zeros(137)
for i in mri_int:
    all_idx[i] = 1

missing_cases = []
for i in range(1,137,1):
    if all_idx[i] != 1:
        missing_cases.append(i)

np.array(missing_cases)

133


array([ 73,  75, 132])

In [ ]:
from glob import glob
import os
import numpy as np

mris = glob('endonasal_mri_v2/MRIs_ALL/*_tumor_f.nii.gz')
mri_int = []
for mri in mris:
    mri_file = os.path.basename(mri).split('_')[0]
    mri_int.append(mri_file)
#     print(mri_file)
mri_int = np.array(mri_int).astype(int)
mri_int.sort()
print(len(mri_int))
all_idx = np.zeros(137)
for i in mri_int:
    all_idx[i] = 1

missing_cases = []
for i in range(1,137,1):
    if all_idx[i] != 1:
        missing_cases.append(i)

np.array(missing_cases)

135


array([73])

In [ ]:
!pip -q install nibabel SimpleITK

In [ ]:
from glob import glob
import os
import numpy as np
import shutil
import nibabel as nib
import numpy as np
import SimpleITK as sitk
# img = nib.load(path)
# img_array = img.get_fdata()


new_root = 'endonasal_mri_v2/endonasal_mri_batch2/'

mris = glob('endonasal_mri_v2/MRIs_ALL/*_carotids_f.nii.gz')
mri_int = []
for mri in mris:
    mri_file = os.path.basename(mri).split('_')[0]
    folder_order = str(mri_file).zfill(3)
    folder_name = 'mri_' + folder_order
    folder_dir = os.path.join(new_root,folder_name)
    os.makedirs(folder_dir, exist_ok=True)


    mask1 = nib.load(mri.replace('carotids', 'tumor'))
    mask1_array = mask1.get_fdata()
    #mask1_array[mask2_array==1] = 2

    mask2 = nib.load(mri)
    mask2_array = mask2.get_fdata()
    mask2_array[mask2_array==1] = 2
    mask2_array[mask1_array==1] = 1
    mask_nifti = nib.Nifti1Image(mask2_array, mask1.affine, header=mask1.header)
    mask_dst = os.path.join(folder_dir, 'mri_'+folder_order+'_mask.nii.gz')
    nib.save(mask_nifti, mask_dst)


    mri_src = os.path.join(os.path.dirname(mri), mri_file+'_T1.nii.gz')
    mri_dst = os.path.join(folder_dir, 'mri_'+folder_order+'_t1c.nii.gz')
    shutil.copy2(mri_src, mri_dst)

    #mri_t1c = nib.load(mri_src)
    #mri_t1c_array = mri_t1c.get_fdata()
    #img_nifti = nib.Nifti1Image(mri_t1c_array, mri_t1c.affine, header=mri_t1c.header)
    #nib.save(img_nifti, mri_dst)

    #To reduce the data type
    #print(f'Data type (from get_fdata): {mri_t1c_array.dtype}')
    #mri_t1c_array = mri_t1c_array.astype(np.int32)

    #To use sitk
    #mri_t1c = sitk.ReadImage(mri_src)
    #img_array = sitk.GetArrayFromImage(mri_t1c)
    #img_sitk = sitk.GetImageFromArray(img_array)
    #img_sitk.SetSpacing(mri_t1c.GetSpacing())
    #img_sitk.SetDirection(mri_t1c.GetDirection())
    #img_sitk.SetOrigin(mri_t1c.GetOrigin())
    #writer = sitk.ImageFileWriter()
    #mri_dst = os.path.join(folder_dir, 'mri_'+folder_order+'_t1c_sitk.nii.gz')
    #writer.SetFileName(mri_dst)
    #writer.Execute(img_sitk)

    print(os.path.join(os.path.dirname(mri), mri_file+'_T1.nii.gz'))
    #break

endonasal_mri_v2/MRIs_ALL/4_T1.nii.gz
endonasal_mri_v2/MRIs_ALL/131_T1.nii.gz
endonasal_mri_v2/MRIs_ALL/119_T1.nii.gz


In [ ]:
endonasal_mri_v2/endonasal_mri_batch2/